import Navbar from "@/components/Navbar";
import ProfileCard from "@/components/ProfileCard";
import { Libre_Franklin } from "next/font/google";

const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          className={`
          ${libreFranklin.className} 
          p-25 antialiased 
          bg-[#1D1D1D] 
          grid grid-cols-[2fr_4fr_0.2fr] 
          gap-4
        `}
        >
          <ProfileCard />
          <div>{children}</div>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
